### Get all flights with page 0 and limit 10
GET http://localhost:8090/flights?page=0&limit=10
Content-Type: application/json

### Get flight by id
GET http://localhost:8090/flights/5010
Content-Type: application/json

### Get all seat numbers for flight by id
GET http://localhost:8090/flights/1/seat_numbers
Content-Type: application/json

### Create new flight
POST http://localhost:8090/flights
Content-Type: application/json

{
    "number": "AA0718",
    "departure": "2017-07-16T09:35:00Z",
    "arrival": "2017-07-16T10:30:00Z",
    "status": "Scheduled",
    "delay": null,
    "aircraft_id": 1,
    "airport_departure_id": 1,
    "airport_arrival_id": 2,
    "fare_tariff_id": 1
}

### Update flight by id
PUT http://localhost:8090/flights/5010
Content-Type: application/json

{
  "number": "AA0718",
  "departure": "2017-07-16T09:35:00Z",
  "arrival": "2017-07-16T10:30:00Z",
  "status": "Delayed",
  "delay": 10,
  "aircraft_id": 104,
  "airport_departure_id": 1,
  "airport_arrival_id": 2,
  "fare_tariff_id": 1
}

### Cancel flight by id
PUT http://localhost:8090/flights/cancel/9999?ticket_discount_percentage=10

### Delete flight by id
DELETE http://localhost:8090/flights/5010