### Get all tickets with page 0 and limit 10
GET http://localhost:8090/tickets?page=0&limit=10
Content-Type: application/json

### Get ticket by id
GET http://localhost:8090/tickets/1
Content-Type: application/json

### Create a new ticket
POST http://localhost:8090/tickets
Content-Type: application/json

{
  "number": "0008386672215",
  "class": "Economy",
  "seat_number": "12A",
  "passenger_full_name": "Paul Smith",
  "flightId": 9999,
  "customerId": "35645ea7-2b38-430d-aab8-f72302cdc2c8"
}

### Change seat number by id
PUT http://localhost:8090/tickets/5280/change_seat_number?seatNumber=2A
Content-Type: application/json

### Upgrade ticket class by id
PUT http://localhost:8090/tickets/5305/upgrade_ticket_class?new_ticket_class=Premium
Content-Type: application/json

### Transfer ticket by id
PUT http://localhost:8090/tickets/5293/transfer?flight_id=9999
Content-Type: application/json

### Delete ticket by id
DELETE http://localhost:8090/tickets/5281